### PR TITLE
Enable package-based CI

### PR DESCRIPTION
**Pull request by sobolevnrm**
Enable continuous integration testing using pytest.

@speleo3 and @orbeckst - this is just FYI.  Unless you object, I'll merge into master.

### CODE REVIEW

**Comment by speleo3** [comment]
nice!

**Comment by speleo3** [comment]
same here, no experience with GH actions (but with appveyor, circleci, gitlab)

**Comment by sobolevnrm** [comment]
@speleo3 & @orbeckst -- I think this works.  Do you approve the merge?

**Comment by orbeckst** [comment]
Have you changed settings on GitHub so that in the future PR merges will require the CI to pass first or is it still advisory?

**Comment by sobolevnrm** [comment]
> Have you changed settings on GitHub so that in the future PR merges will require the CI to pass first or is it still advisory?

Just advisory for now.  Do others feel strongly about requiring it to pass?

**Comment by intendo** [comment]
Just an observation, I have noticed that many github sites fail different tests. Sometimes, it is because Github Actions or Travis, or Appveyor change their images and/or environments. APBS-PDB2PQR used to pass Travis on the Mac environment just fine and now it fails and I have not taken the time to go figure out what changed in Travis to make it fail.

**Comment by sobolevnrm** [comment]
> Just an observation, I have noticed that many github sites fail different tests. Sometimes, it is because Github Actions or Travis, or Appveyor change their images and/or environments. APBS-PDB2PQR used to pass Travis on the Mac environment just fine and now it fails and I have not taken the time to go figure out what changed in Travis to make it fail.

I think we should just make it advisory.

**Comment by orbeckst** [comment]
Advisory is fine.

Unless you pin your dependencies in the CI, it's hard work to keep CI passing in a changing and updating environment – we have plenty of these issues in MDAnalysis where we require passing tests in all environments before a merge. (Coverage is advisory, although typically no reviewer approves if not ~90% of the diff are covered by tests.)

**Pull request merged**
