### PR TITLE
Attempt to add coverage.py to testing workflow

### PR DESCRIPTION
**Pull request by sobolevnrm**

### CODE REVIEW

**Comment by sobolevnrm** [comment]
I'm pretty happy with this.  It runs both tests and coverage analysis and saves the output of the coverage analysis as artifacts.

**Comment by sobolevnrm** [comment]
> Where does one see the result of the coverage test?

The results are provided as artifacts associated with the action; e.g., https://github.com/jensengroup/propka/actions/runs/141911691

> Is there a way to make it report the coverage of the diff and the total coverage change as part of the Pr checks? (This is what I am used to from codecov.io.)

Not that I've figure out... sorry.

**Comment by orbeckst** [comment]
Would be ok with trying out codecov?

**Comment by sobolevnrm** [comment]
Absolutely; please do!

________________________________

**Pull request merged**
