### PR TITLE
Update CI and docs for Python up to py311

### PR DESCRIPTION
**Pull request by IAlibay**
## Summary of changes

- Update CI to add py310 and py311
- Added cron entry for CI
- Added classifiers for new python versions
- Removed universal wheels (propka doesn't support py2.x anymore)

### CODE REVIEW

**Comment by speleo3** [comment]
What's the rational for triggering two builds a week?

**Comment by IAlibay** [comment]
> What's the rational for triggering two builds a week?

We've been doing twice a week in other places (MDAnalysis, etc...) since we have lots of dependencies that update randomly, but I agree that it's probably too much for this repo.

Once a week or more infrequently? I suspect the cron job is going to get disabled once in a while anyways if the commit frequency is too low (> 6 weeks).

**Comment by speleo3** [comment]
Thanks for clarifying. Once a week sounds good to me, we can always change it if needed.

**Review by speleo3 — APPROVED** [review]

**Review by sobolevnrm — APPROVED** [review]

**Comment by sobolevnrm** [comment]
Thank you for the PR, @IAlibay !

**Pull request merged**
